### PR TITLE
#240 Polygon node

### LINKED ISSUE #240: Polygon node
1.希望增加全国著名湖泊（如西湖）和湖泊通用模型
2.优化河流画法，不需要连接两点绘制或隐藏连接点

### PR DESCRIPTION
**Pull request by thekingofcity**
This should fix #240

### CODE REVIEW

**Comment by thekingofcity** [comment]
Not ready due to off-putting input fields :(

**Comment by langonginc** [comment]
Is there any way to add a click hook on each node of a polygon to move nodes' offset?

**Comment by thekingofcity** [comment]
> Is there any way to add a click hook on each node of a polygon to move nodes' offset?

Sure. It's possible to add some hooks for nodes of a polygon and change the shape of it when nodes are moving. This is exactly what I want to implement. But there are two obstacles :( Time/priority and the performance effect this particular hook may cause. I'm talking about hundreds of polygons with thousands of nodes inside each of them.

**Comment by langonginc** [comment]
> > Is there any way to add a click hook on each node of a polygon to move nodes' offset?
> 
> 
> 
> Sure. It's possible to add some hooks for nodes of a polygon and change the shape of it when nodes are moving. This is exactly what I want to implement. But there are two obstacles :( Time/priority and the performance effect this particular hook may cause. I'm talking about hundreds of polygons with thousands of nodes inside each of them.
> 
> 

Yep, it is quite massive. 🤨

**Comment by thekingofcity** [comment]
Another thing about this approach is whether to make a strong reference between nodes inside a polygon and the polygon itself. If there is no constraint about node deletion, we might be in a place where there is no node inside a polygon. However, if there is such a constraint, how will such a constraint be implemented is still an open question. Will polygon reference be a special case for virtual nodes? And how to handle constraints during copy and paste. If only a weak reference exists, then how will a polygon behave on empty nodes? Where should it be placed without any children's node information? I would prefer the latter way but so many questions need to be figured out but this does not have enough priority.

**Comment by langonginc** [comment]
> we might be in a place where there is no node inside a polygon. 

What is the meaning of no node inside a polygon? IMO, node is on the polygon so there is no way that a node is _in_ a polygon.

**Comment by thekingofcity** [comment]
> > we might be in a place where there is no node inside a polygon.
> 
> What is the meaning of no node inside a polygon? IMO, node is on the polygon so there is no way that a node is _in_ a polygon.

Right. It makes no sense when there is no node inside a polygon. But if you do not have any constraints for these nodes, they could be deleted by the users by default, as they are first general nodes and then specific nodes for this polygon.

By constraints I mean some additional logic that forbids nodes to be deleted/managed by users.

**Pull request closed without merging**
