### PR TITLE
Add buttons to change colors of dual-color style line

### PR DESCRIPTION
**Pull request by OriginCode**
This change adds color field buttons to dual-color style.

### CODE REVIEW

**Comment by thekingofcity** [comment]
Hi, thanks for the contribution. Dual color style is way before the upgrade on the color field that supports different keys. And during that upgrade, this is not updated as well.

BTW I believe the current name of _Shanghai Maglev style_ is not accurate after this change, so it might also be updated.

NOTE: We are on the final release of v5 soon, which includes renaming the current v5 branch to main and main to v3 I suppose. Would you still targeting the current v3 main branch?

**Comment by OriginCode** [comment]
> Hi, thanks for the contribution. Dual color style is way before the upgrade on the color field that supports different keys. And during that upgrade, this is not updated as well.
> 
> BTW I believe the current name of _Shanghai Maglev style_ is not accurate after this change, so it might also be updated.
> 
> NOTE: We are on the final release of v5 soon, which includes renaming the current v5 branch to main and main to v3 I suppose. Would you still targeting the current v3 main branch?

Then should I make changes on v5 branch instead?

**Comment by thekingofcity** [comment]
Yes, if such changes could be made today or tomorrow. I'll start renaming the branch after this is merged.

**Comment by OriginCode** [comment]
Yeah sure, I'll open another PR preceding this one.

**Comment by OriginCode** [comment]
Superseded by #814

**Pull request closed without merging**
