### PR TITLE
#488 Show a warning element for unknown nodes&lines

### LINKED ISSUE #488: #488 Show a warning element for unknown nodes&lines
Instead of throwing a fatal error :(

### PR DESCRIPTION
**Pull request by thekingofcity**
This should close #488 

Illegal nodes is not in this feature's scope as illegal nodes won't cause a crash but unknown nodes will :(

### CODE REVIEW

**Comment by langonginc** [comment]
image

I cannot see my node whose id is illegal. Is this what we expected?

**Comment by thekingofcity** [comment]
> image
> 
> I cannot see my node whose id is illegal. Is this what we expected? And the station's `x, y` was changed.

What do you mean by seeing node? `x, y` should be changed, something is not going right here :(

**Comment by langonginc** [comment]
I can see a '?' if I change the type of a station to _something illegal_. But I can see nothing if I change the its id and type both to illegal.

**Comment by thekingofcity** [comment]
> I can see a '?' if I change the type of a station to _something illegal_. But I can see nothing if I change the its id and type both to illegal.

Oh, illegal id. Nodes with illegal id should not be seen by design, as they are filled out in [here](https://github.com/railmapgen/rmp/blob/133903bd5ed94e6972e10064e13cd8a90f92d4a6/src/util/process-elements.ts#L23) and [here](https://github.com/railmapgen/rmp/blob/133903bd5ed94e6972e10064e13cd8a90f92d4a6/src/util/process-elements.ts#L87).

IMO we are dealing with unknown nodes, not illegal nodes. As far as I can see, there is no chance that nodes will start without `stn` or `misc_node` so there is no need to show a question mark for those illegal nodes :)

**Comment by thekingofcity** [comment]
Okay, so 0 for x and y in illegal nodes is by design and is unchanged in this pr. If this is not the expected behavior, another issue should track this :)

https://github.com/railmapgen/rmp/blob/133903bd5ed94e6972e10064e13cd8a90f92d4a6/src/components/panels/details/node-position-section.tsx#L26

**Review by langonginc — APPROVED** [review]
I have no other comments now 😙

**Comment by thekingofcity** [comment]
FYI, this is the save I used in testing :)

[unknown nodes.json](https://github.com/railmapgen/rmp/files/13445730/unknown.nodes.json)

**Pull request merged**
